node_types:
  cloudify.example.Example:
    derived_from: cloudify.nodes.Root
    interfaces:
      cloudify.interfaces.lifecycle:
        start:
          implementation: example.cloudify_plugin.tasks.write_to_file

plugins:
  example:
    executor: central_deployment_agent
    source: https://github.com/EarthmanT/cloudify-plugin-example/archive/master.zip